FROM ubuntu:latest

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y wget openjdk-8-jdk

RUN wget -q https://launcher.mojang.com/download/Minecraft.deb && \
    dpkg -i Minecraft.deb && \
    rm Minecraft.deb

ENV DISPLAY=:0

CMD minecraft-launcher